In [2]:
import numpy as np
import methods as mt
import csv
from scipy.optimize import linear_sum_assignment


In [3]:
with open('train.txt', newline='') as train:
   reader = csv.reader(train, delimiter=' ')
   stringTrainRows = []
   for row in reader:
        stringTrainRows.append(row)
trainData = []
for row in stringTrainRows:
    trainData.append([int(row[0]),row[1]])
print(trainData)


with open('valid.txt', newline='') as train:
   reader = csv.reader(train, delimiter=' ')
   stringTrainRows = []
   for row in reader:
        stringTrainRows.append(row)
validData = []
for row in stringTrainRows:
    validData.append([int(row[0]),row[1]])
print(validData)


[[11808, 'a'], [15905, 'a'], [17157, 'a'], [35016, 'a'], [17964, 'a'], [12556, 'a'], [21376, 'a'], [22527, 'a'], [42269, 'a'], [21990, 'a'], [31640, 'a'], [20077, 'a'], [23405, 'a'], [10830, 'a'], [20078, 'a'], [2250, 'a'], [41286, 'a'], [23401, 'a'], [22711, 'a'], [22712, 'a'], [28711, 'a'], [881, 'a'], [26552, 'a'], [42414, 'a'], [27115, 'a'], [36034, 'a'], [27305, 'a'], [25869, 'a'], [2697, 'a'], [27931, 'a'], [42356, 'a'], [24617, 'a'], [1602, 'a'], [23972, 'a'], [18857, 'a'], [272, 'a'], [18858, 'a'], [9105, 'a'], [3004, 'a'], [28548, 'a'], [37953, 'a'], [2950, 'a'], [22181, 'a'], [2340, 'a'], [20425, 'a'], [1558, 'a'], [16982, 'a'], [22793, 'a'], [26284, 'a'], [22606, 'a'], [560, 'i'], [4201, 'i'], [1132, 'i'], [1372, 'i'], [251, 'i'], [6390, 'i'], [10560, 'i'], [14922, 'i'], [21824, 'i'], [3180, 'i'], [6287, 'i'], [7963, 'i'], [10101, 'i'], [1102, 'i'], [13467, 'i'], [15379, 'i'], [1689, 'i'], [21821, 'i'], [23540, 'i'], [25529, 'i'], [2746, 'i'], [29473, 'i'], [3441, 'i'], [390

In [4]:
roots = []
roots = mt.importMolecule('gxl')
trainNodes = []
validNodes = []
trainEdges = []
validEdges = []
listedMolecules = mt.moleculeToList(roots)
nodesList = listedMolecules[0]
edgesList = listedMolecules[1]
for i in range(0, len(nodesList)):
    for row in trainData:
        if (row[0] == nodesList[i][0]):
            trainNodes.append(nodesList[i])
            trainEdges.append(edgesList[i])
    for row in validData:
        if (row[0] == nodesList[i][0]):
            validNodes.append(nodesList[i])
            validEdges.append(nodesList[i])



In [5]:
distanceMatrix = np.zeros((len(trainNodes), len(validNodes)))
for i in range(0, len(trainNodes)):
    for j in range(0, len(validNodes)):
        costMatrix = mt.costMatrix(trainNodes[i][1], trainEdges[i][1], validNodes[j][1], validEdges[j][1], cn = 1 ,ce = 0.8)
        distanceMatrix.itemset((i,j), costMatrix[linear_sum_assignment(costMatrix)].sum())
print(distanceMatrix)

[[ 8.  9. 10. ... 51.  6.  7.]
 [ 8.  7.  4. ... 53.  6.  5.]
 [ 4.  5.  2. ... 47.  4.  3.]
 ...
 [ 7.  6.  7. ... 50.  3.  4.]
 [10.  3.  4. ... 49.  6.  7.]
 [ 5. 10.  5. ... 48.  9.  6.]]


In [6]:
accuracy = mt.knnsearch(5, validData, trainData, distanceMatrix)
print(accuracy)

13210   13210
14050   14050
5050   5050
14362   14362
23402   23402
16344   16344
21988   21988
29387   29387
17875   17875
30122   30122
42268   42268
20090   20090
33115   33115
18854   18854
21558   21558
28860   28860
20075   20075
40331   40331
19384   19384
23667   23667
35895   35895
41793   41793
41813   41813
27984   27984
28301   28301
24818   24818
40677   40677
31510   31510
36848   36848
21377   21377
28793   28793
19386   19386
42364   42364
42155   42155
42158   42158
42351   42351
35139   35139
35134   35134
20782   20782
35136   35136
23668   23668
1612   1612
20417   20417
15751   15751
9693   9693
32611   32611
16975   16975
41540   41540
30419   30419
7400   7400
11182   11182
6074   6074
10568   10568
171   171
3937   3937
94   94
1318   1318
17222   17222
23570   23570
4619   4619
7414   7414
91   91
1019   1019
12207   12207
14925   14925
1623   1623
20449   20449
22445   22445
2468   2468
26606   26606
28590   28590
32872   32872
36533   36533
40   40
4963   496